Lab makes config file for P7
jamadaha/P7 pull request #162
Opened 2022-10-26 11:43 UTC by matblicher

Closes #151

2022-10-28 06:11 UTC, kris701 commented on runP7.py
> +    settingscontent += "PATH:domain=" + task.domain_file + "\n"
It might be a better idea to work out of one of the current settings files, and then modify what is needed. Since i think it will become a little annoying over time to having to keep adding more and more things in here, instead of just adding the things thats relevant for Lab

2022-10-28 16:46 UTC, kris701 requested changes

2022-10-28 16:46 UTC, kris701 commented on settingsLabMultiple.ini
> +problem=prob01.pddl,prob02.pddl:p01.pddl,p02.pddl
Maybe follow the same syntax as the rest of the config style for this? so it would be `PATH:benchmarks...` and `STRING:domain...`
I know it does not have anything to do with the actual config file for the program, but it is nice to follow the same style

2022-10-30 08:51 UTC, matblicher commented on settingsLabMultiple.ini
> +problem=prob01.pddl,prob02.pddl:p01.pddl,p02.pddl
Sure, I had that at first but thought it might be confusing since it did not have a function.

2022-10-30 12:47 UTC, kris701 commented
I tried to quickly merge Main into this, however no matter what i do it always says that it cant find fast-downward.py
Not sure why, maybe @matblicher can look into this?

2022-10-31 07:27 UTC, matblicher commented
> I tried to quickly merge Main into this, however no matter what i do it always says that it cant find fast-downward.py Not sure why, maybe @matblicher can look into this?

Have you tried the absolute path to fastdownward?
I have downward and validate at /home/pc so I have a different settingsLab.ini

2022-10-31 08:45 UTC, kris701 approved these changes

2022-10-31 08:45 UTC, merged